// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxzytziqjfjmmtpcznvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4enl0emlxamZqbW10cGN6bnZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5ODg1MzksImV4cCI6MjA2ODU2NDUzOX0.7tG1DDGJxVb7LvLh08BFp4H8x5Maw6zCynnXMyg2X5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});